apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: microservices-architecture-docker-kubernetes
build:
  artifacts:
  - image: kdidi/ms-k8s-service-backend1
    context: microservices/service-backend1
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
  - image: kdidi/ms-k8s-service-backend2
    context: microservices/service-backend2
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
  - image: kdidi/ms-k8s-service-frontend
    context: microservices/service-frontend
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - kubernetes/service-backend1.yaml
    - kubernetes/service-backend2.yaml
    - kubernetes/service-frontend.yaml
