name: Docker Compose CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code 🛎
      uses: actions/checkout@v3    
    # run utility services in the background
    # using docker-compose (see docker-compose.yml file)
    - name: Run docker-compose -d
      run: docker-compose up -d --build
